name: Build JAR and Push to ECR

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Compile Java and create JAR
        run: |
          mkdir -p out
          javac -d out hello.java
          echo "Main-Class: hello" > manifest.txt
          printf "\n" >> manifest.txt
          jar cfm hello.jar manifest.txt -C out .

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::630398150799:role/rushi-java-github
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t hello-app .

      - name: Tag image for ECR
        run: |
          docker tag hello-app:latest 630398150799.dkr.ecr.us-east-1.amazonaws.com/rushi-java-repo:latest

      - name: Push image to ECR
        run: |
          docker push 630398150799.dkr.ecr.us-east-1.amazonaws.com/rushi-java-repo:latest
